steps:
  - label: ":console:"
    command: "script.sh"
    parallelism: 5
    agents:
      queue: linux-amd64-gpu
  - label: ":console:"
    command: "script.ps1"
    artifact_paths: "artifacts/*"
    parallelism: 5
    agents:
      queue: windows-gpu
